### ISSUE TITLE
Not logging all requests

### ISSUE THREAD

**Issue by bibhas2** [sebastianschramm/openai-cost-tracker#2]
I'm using the ``track-costs`` command with Microsoft GraphRAG. Specifically, I'm going through the [Getting Started ](https://microsoft.github.io/graphrag/get_started/) tutorial. For example, when indexing, I'm running the command:

```
track-costs graphrag index --root ./ragtest
```

The tool is correctly logging all requests to build the index. That's great. But, when I run a query like this:

```
 track-costs graphrag query --root ./ragtest --method local \
  --query "Who is Scrooge and what are his main relationships?"
```

Only the request to embed the prompt is logged:

```json
{
 "span_name": "openai.embeddings",
 "start_time": 1736524041871925969,
 "end_time": 1736524042150759290, 
 "gen_ai.prompt.0.content": "Who is Scrooge and what are his main relationships?"
...}
```

I don't see the final request with the context and the response. For every query only the above request is being logged.

**Comment by quying** [comment]
Same here. Have you found the solution for this problem?

**Comment by bibhas2** [comment]
@quying My solution was to use Ollama from GraphRAG and observe the network communication using ``tcpdump``. Ollama's API is compatible with OpenAI, so, GraphRAG will work. The quality of responses won't be as good from a small local model. But, that's OK. My goal was to observe the LLM prompts and responses. 

Below are the high level steps. They will work in Ubuntu or Windows WSL.

Install Ollama.

Install ``tcpdump``.

Ollama pull the local LLM model and embedding model. I used ``llama3.1`` and ``bge-large`` respectively.

Configure ``settings.yaml`` of GraphRAG to:

1. Use local models from Ollama. 
2. Lower ``num_threads``, ``concurrent_requests``, ``max_tokens`` and chunk ``size`` to work within your machine's limit.

Example LLM:

```yaml
llm:
  api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
  type: openai_chat # or azure_openai_chat
  model: llama3.1
  max_tokens: 2000
  model_supports_json: false # recommended if this is available for your model.
  api_base: http://127.0.0.1:11434/v1
```

Example embedding model:

```yaml
embeddings:
  async_mode: threaded # or asyncio
  vector_store:
    type: lancedb
    db_uri: 'output/lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    api_base: http://127.0.0.1:11434/v1
    type: openai_embedding # or azure_openai_embedding
    model: bge-large:latest
    concurrent_requests: 1
```

Before you index or query using GraphRAG, start monitoring port 11434.

```
sudo tcpdump -A -t -i any port 11434 and 'tcp[13] & 8 != 0'
```

Index and query using GraphRAG. You should see the communication in the ``tcpdump`` output.
